POST http://localhost:3000/basic/insert HTTP/1.1
  Content-Type: application/json
  
  {
	"data": [
		{
			"lectureId": "1000000001",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "1",
			"startTime": "1000",
			"endTime": "1100"
		},
		{
			"lectureId": "1000000002",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "1",
			"startTime": "1030",
			"endTime": "1130"
		},
		{
			"lectureId": "1000000003",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "2",
			"startTime": "1000",
			"endTime": "1100"
		},
		{
			"lectureId": "1000000004",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "2",
			"startTime": "1200",
			"endTime": "1300"
		},
		{
			"lectureId": "1000000005",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "2",
			"startTime": "1030",
			"endTime": "1230"
		},
		{
			"lectureId": "1000000006",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "3",
			"startTime": "1000",
			"endTime": "1100"
		},
		{
			"lectureId": "1000000007",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "3",
			"startTime": "1200",
			"endTime": "1300"
		},
		{
			"lectureId": "1000000008",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "3",
			"startTime": "0900",
			"endTime": "1400"
		},
		{
			"lectureId": "1000000009",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "3",
			"startTime": "1030",
			"endTime": "1230"
		},
		{
			"lectureId": "1000000010",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "4",
			"startTime": "1000",
			"endTime": "1100"
		},
		{
			"lectureId": "1000000011",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "4",
			"startTime": "1200",
			"endTime": "1300"
		},
		{
			"lectureId": "1000000012",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "4",
			"startTime": "0900",
			"endTime": "1400"
		},
		{
			"lectureId": "1000000013",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "4",
			"startTime": "1030",
			"endTime": "1230"
		},
		{
			"lectureId": "1000000014",
			"facultyId": "1100000000",
			"semesterId": "1110000000",
			"dayOfWeek": "4",
			"startTime": "1215",
			"endTime": "1425"
		}
	]
}