GET http://localhost:3000/basic/data?dayOfWeek=3 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/basic/insert HTTP/1.1
Content-Type: application/json

{
    "data" : [
        {
            "lectureId": 1111222266,
            "semesterId": 1111222233,
            "facultyId": 1111222233,
            "dayOfWeek": 3,
            "startTime": "1200",
            "endTime": "1400"
        },
        {
            "lectureId": 1000999988,
            "semesterId": 1000999988,
            "facultyId": 1000999978,
            "dayOfWeek": 3,
            "startTime": "1500",
            "endTime": "1700"
        },
        {
            "lectureId": 2288888844,
            "semesterId": 8888888844,
            "facultyId": 8888888844,
            "dayOfWeek": 2,
            "startTime": "1200",
            "endTime": "1400"
        }
    ]
}

###

POST http://localhost:3000/basic/insert HTTP/1.1
Content-Type: application/json

{
    "data" : [
        {
            "lectureId": 1234567891,
            "semesterId": 1234567890,
            "facultyId": 1234567890,
            "dayOfWeek": 3,
            "startTime": "1400",
            "endTime": "1600"
        }
    ]
}