@geturl = http://localhost:3000/advance/data
@getMethod = GET

{{getMethod}} {{geturl}} HTTP/1.1
Content-Type: application/json

###
# GET http://localhost:3000/advance/data?page=10&pageSize=5 HTTP/1.1
{{getMethod}} {{geturl}}?facultyId=1100000000&semesterId=1110000000&dayOfWeek=4&page=0&pageSize=3 HTTP/1.1
Content-Type: application/json

###
@url = http://localhost:3000/advance/insert
@httpMethod = POST

# @name EmptyData
{{httpMethod}} {{url}} HTTP/1.1
Content-Type: application/json

{
	"data": []
}

###

{{httpMethod}} {{url}} HTTP/1.1
Content-Type: application/json

{
    "data": [
        {
            "technicianId":1237867890,
            "semesterId":9999999991,
            "facultyId":9999999991,
            "dayOfWeek":1,
            "startTime":"1352",
            "endTime":"2134"
        }
    ]
}

###
# @name BulkInsert

{{httpMethod}} {{url}} HTTP/1.1
Content-Type: application/json

{
    "data": [
        {
            "technicianId":1234567890,
            "semesterId":9999999991,
            "facultyId":9999999991,
            "dayOfWeek":1,
            "startTime":"1352",
            "endTime":"2134"
        },
        {
            "technicianId":9999999991,
            "semesterId":9999999992,
            "facultyId":9999999991,
            "dayOfWeek":2,
            "startTime":"0912",
            "endTime":"1123"
        },
        {
            "technicianId":9999999992,
            "semesterId":9999999991,
            "facultyId":9999999991,
            "dayOfWeek":3,
            "startTime":"1534",
            "endTime":"2145"
        },
        {
            "technicianId":9999999993,
            "semesterId":9999999992,
            "facultyId":9999999991,
            "dayOfWeek":4,
            "startTime":"2143",
            "endTime":"2323"
        },
        {
            "technicianId":9999999994,
            "semesterId":9999999991,
            "facultyId":9999999991,
            "dayOfWeek":5,
            "startTime":"1111",
            "endTime":"2233"
        },
        {
            "technicianId":9999999995,
            "semesterId":9999999992,
            "facultyId":9999999991,
            "dayOfWeek":6,
            "startTime":"0000",
            "endTime":"0001"
        },
        {
            "technicianId":9999999996,
            "semesterId":9999999991,
            "facultyId":9999999992,
            "dayOfWeek":7,
            "startTime":"2222",
            "endTime":"2223"
        },
        {
            "technicianId":9999999997,
            "semesterId":9999999992,
            "facultyId":9999999992,
            "dayOfWeek":1,
            "startTime":"2350",
            "endTime":"2359"
        },
        {
            "technicianId":9999999998,
            "semesterId":9999999991,
            "facultyId":9999999992,
            "dayOfWeek":2,
            "startTime":"1234",
            "endTime":"1345"
        },
        {
            "technicianId":9999999999,
            "semesterId":9999999992,
            "facultyId":9999999992,
            "dayOfWeek":3,
            "startTime":"2313",
            "endTime":"2355"
        }
    ]
}

###

# @name PartialDuplicate

{{httpMethod}} {{url}} HTTP/1.1
Content-Type: application/json

{
	"data": [
        {
            "technicianId":9999999999,
            "semesterId":9999999992,
            "facultyId":9999999992,
            "dayOfWeek":3,
            "startTime":"2313",
            "endTime":"2355"
        },
        {
            "technicianId":1234567891,
            "semesterId":9999999992,
            "facultyId":9999999992,
            "dayOfWeek":3,
            "startTime":"2313",
            "endTime":"2355"
        }
    ]
}

###

# @name InvalidMissingField

{{httpMethod}} {{url}} HTTP/1.1
Content-Type: application/json

{
	"data": [
        {
            "technicianId": 9934577891,
            "semesterId": 4234567891,
            "facultyId": 1234567890,
            "startTime": "0152",
            "endTime": "0241"
        }
    ]
}

###

@resulturl = http://localhost:3000/advance/result
@resultMethod = GET


###
# @name Result

{{resultMethod}} {{resulturl}}?semesterId=9999999991&facultyId=9999999991&dayOfWeek=1
Content-Type: application/json
